### ISSUE TITLE
21.10: desktop icons pop out of running apps when changing workspaces

### ISSUE THREAD

**Issue by ianhundere** [pop-os/desktop-icons-ng#22]
**How did you upgrade to `21.10`? (Fresh install / Upgrade)**

via the gui/upgrade menu from `21.04`

**Issue/Bug Description:**
when you change workspaces, if you have icons on your desktop they'll momentarily pop out until you've changed workspaces.

**Steps to reproduce (if you know):**
- have desktop icons
- change workspaces

**Expected behavior:**
deskstop icons shouldn't bleed through running apps

**Previous open issue:**
[deskstop icons shouldn't bleed through running apps](https://github.com/pop-os/beta/issues/214)

**Comment by jacobgkau** [comment]
This was fixed by https://github.com/pop-os/desktop-icons-ng/pull/20, but it looks like the new version hasn't been released from proposed yet.

**Comment by jacobgkau** [comment]
https://github.com/pop-os/repo-release/blob/e791ee3cb82fbdfd3af1f9fa5946bfb519ddabe2/sync#L271 shows that the new version _should_ be currently released, although my system doesn't see it available from the Impish repo.

**Comment by ianhundere** [comment]
thanks for the heads up, i'll keep my eyes peeled.

**Comment by ianhundere** [comment]
and it's been released. this can be closed :o)

**Comment by ianhundere** [comment]
...actually, i spoke too soon. the extension errors after some time.
![image](https://user-images.githubusercontent.com/138915/148652266-d9a01e14-5428-4447-b794-10aba0364a22.png)
![image](https://user-images.githubusercontent.com/138915/148652275-bdf7ece2-ca76-4070-8db9-0cfc6e0c069c.png)

**Comment by jacobgkau** [comment]
@ianhundere That does not sound like the same issue as what you reported here. Can you please provide a screenshot of the entire Extensions app? The actual error from `journalctl` would also be helpful.

**Comment by ianhundere** [comment]
@jacobgkau sure thing
```
Jan 10 08:34:15 t14s gnome-shell[2182]: Extension ding@rastersoft.com already installed in /home/ianfundere/.local/share/gnome-shell/extensions/ding@rastersoft.com. /usr/share/gnome-shell/extensions/ding@rastersoft.com will not be loaded
                                        Since I'm overriding values in that const an error show might show up.
```

```
Jan 10 08:35:37 t14s gnome-shell[2182]: JS ERROR: Extension ding@rastersoft.com: Error: A different version was loaded previously. You need to log out for changes to take effect.
```
some new updates came through as well. i'll update / restart and report back.

**Comment by ianhundere** [comment]
and it looks good. looks like the update provided in today's pop!_os updates resolved it whereas the update i used via extensions.gnome.org did not.

thanks for all the help / clarification :rocket:
