### ISSUE TITLE
Packaged version doesn't respect language settings

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/desktop-icons-ng#4]
The extension's right-click menu and preferences dialog do not respect the system's language settings (they are always in English, even if the language was changed in Settings -> Region & Language and the session was restarted.) If I install the extension from extensions.gnome.org, it _does_ respect the language settings.

Tested with Portuguese (Brazil) and French, both of which have translation files in the package.

**Comment by ids1024** [comment]
Strange. The translation files are installed, and work in Python:

```python
import gettext
gettext.translation('ding', languages=['es']).gettext('Show a context menu item to delete permanently')
```

I guess it isn't loading translations from the normal system directory for some reason...

**Comment by ids1024** [comment]
Ah yes, I suppose it's the way the `bindtextdomain` call is written. Should be easy to fix.
