### ISSUE TITLE
Is this installed/enabled automatically?

### ISSUE THREAD

**Issue by davidskeck** [pop-os/desktop-icons-ng#9]
I am running the latest Pop!_OS and I suddenly got desktop icons. I never knowingly installed this. Just curious if this is being pushed out or if I messed up somehow.

**Comment by mmstick** [comment]
Yes, this is installed by default. Has been for a very long time.

**Comment by davidskeck** [comment]
Gotcha. I must have accidentally enabled it somehow. Thanks!
